#!/usr/bin/env bash

THEME="$THEME"

if [ "$THEME" == "light" ]; then
    cat <<EOF
set default-bg                  "#e0def4"
set default-fg                  "#000000"

set statusbar-fg                "#e0def4"
set statusbar-bg                "#555169"

set inputbar-bg                 "#6e6a86"
set inputbar-fg                 "#ebbcba"

set notification-bg             "#e0def4"
set notification-fg             "#555169"

set notification-error-bg       "#f6c177"
set notification-error-fg       "#555169"

set notification-warning-bg     "#ebbcba"
set notification-warning-fg     "#555169"

set highlight-color             "#ebbcba"
set highlight-active-color      "#eb6f92"

set completion-bg               "#6e6a86"
set completion-fg               "#ebbcba"

set completion-highlight-fg     "#26233a"
set completion-highlight-bg     "#ebbcba"

set recolor-lightcolor          "#e0def4"
set recolor-darkcolor           "#000000"
EOF
else
    cat <<EOF
set default-bg                  "#000000"
set default-fg                  "#e0def4"

set statusbar-fg                "#e0def4"
set statusbar-bg                "#555169"

set inputbar-bg                 "#6e6a86"
set inputbar-fg                 "#ebbcba"

set notification-bg             "#e0def4"
set notification-fg             "#555169"

set notification-error-bg       "#f6c177"
set notification-error-fg       "#555169"

set notification-warning-bg     "#ebbcba"
set notification-warning-fg     "#555169"

set highlight-color             "#ebbcba"
set highlight-active-color      "#eb6f92"

set completion-bg               "#6e6a86"
set completion-fg               "#ebbcba"

set completion-highlight-fg     "#26233a"
set completion-highlight-bg     "#ebbcba"

set recolor-lightcolor          "#e0def4"
set recolor-darkcolor           "#000000"
EOF
fi
