#!/usr/bin/env bash

[ -f ~/.config/user-dirs.dirs ] && source ~/.config/user-dirs.dirs

# dir="${XDG_PICTURES_DIR:-${HOME}/img}"
dir="${HOME}/Imagens/Wallpapers/"
unsplash_dir="${XDG_PICTURES_DIR:-${HOME}/img}/unsplash"
default="$dir/8579cdf9-c136-45e6-8a7e-dc61bced0d35.jpg"
ultima="/home/rwietter/Imagens/Wallpapers/wallhaven-we31gx_1320x768.png"
modo="--bg-fill"
indice=0
i=0
x=$(xdpyinfo | grep dimensions | awk '{print $2}' | awk -F'x' '{print $1}')
y=$(xdpyinfo | grep dimensions | awk '{print $2}' | awk -F'x' '{print $2}')

ajustar() {
	if [ -f "$1" ]; then
		sed -i "s|^ultima=.*|ultima=\"${1}\"|g" $0
		feh --bg-fill "$1"
		# echo "$1" > ~/Imagens/Wallpapers/$(basename $1)
	fi
}

if [ "$2" ]; then
	[ -d $2 ] && dir=$2
else
	[ ! -d $dir ] && mkdir -p $dir
fi

# [ ! -d $unsplash_dir ] && mkdir -p $unsplash_dir
# [ ! -f $default ] && curl -s -L 'https://unsplash.com/photos/mEV-IXdk5Zc/download?force=true' > $default

while read linha; do
    imagens[$i]="$linha"
		echo "$i - ${imagens[$i]}"
    ((i++))
done < <(find "$dir" -type f \( -iname \*.jpg -o -iname \*.png -o -iname \*.jpeg \) | sort -n)

cont=${#imagens[@]}
total=$(($cont-1))

if [ $total -gt 0 ]; then
	for i in "${!imagens[@]}"; do
			# echo "$i - ${imagens[$i]}"
   		if [[ "${imagens[$i]}" = "${ultima}" ]]; then
       		indice=${i}
   		fi
	done
else
	echo "Nenhuma imagem."
	exit 1
fi

if [ ! $1 ]; then
	img=${imagens[$RANDOM % ${#imagens[@]} ]}
elif [ "$1" == "d" ]; then
	img="$unsplash_dir/unsplash-$$.jpg"
	curl -L -s "https://unsplash.it/${x}/${y}?random" > $img
	notify-send "Sucesso" "Imagem <b>$img</b> baixada."
elif [ "$1" == "dd" ]; then
	apagar=$(echo -e "Sim\nNão" | rofi -p "Apagar $(find ~/Imagens/unsplash -type f \( -iname \*.jpg -o -iname \*.png -o -iname \*.jpeg \) | sort -n)?" -dmenu -bw 0 -lines 2 -width 400 -separator-style none -location 0 -hide-scrollbar -padding 5)
	if [ "$apagar" == "Sim" ]; then
		rm $(find ~/Imagens/unsplash -type f \( -iname \*.jpg -o -iname \*.png -o -iname \*.jpeg \) | sort -n)
		notify-send "Sucesso" "Imagem <b>$(find ~/Imagens/unsplash -type f \( -iname \*.jpg -o -iname \*.png -o -iname \*.jpeg \) | sort -n)</b> apagada."
		hsetroot -solid "#2e3440"
	fi
elif [ "$1" == "a" ]; then
	if [ $indice -gt 0 ]; then
		((indice--))
	else
		indice=$total
	fi
	img=${imagens[$indice]}
elif [ "$1" == "p" ]; then
	if [ $indice -lt $total ]; then
		((indice++))
	else
		indice=0
	fi
	echo ${imagens[$indice]} $indice
	img=${imagens[$indice]}
elif [ "$1" == "r" ]; then
	if [ ! -f $HOME/Imagens/Wallpapers ] || [ ! -f $(cat $HOME/Imagens/Wallpapers) ]; then
		echo $default > $HOME/Imagens/Wallpapers
	fi
	img=$(cat $HOME/Imagens/Wallpapers)
fi

ajustar "$img"
